### ISSUE TITLE
Module declares inconsistent path

### ISSUE THREAD

**Issue by michaelbironneau** [eduhenke/go-ocpp#12]
When adding the project to a go module by running `go dep init && go get -v github.com/voltbras/go-ocpp`, there is an error:

```
go: github.com/voltbras/go-ocpp upgrade => v1.0.0
go get: github.com/voltbras/go-ocpp@v1.0.0: parsing go.mod:
	module declares its path as: github.com/eduhenke/go-ocpp
	        but was required as: github.com/voltbras/go-ocpp
```

I think the fix is a simple change to your `go.mod` file replacing `github.com/eduhenke/go-ocpp` by `github.com/voltbras/go-ocpp` in the first line. 

Happy to submit a PR if you prefer.

**Comment by michaelbironneau** [comment]
There are also some internal packages imported from `github.com/eduhenke/go-ocpp` and the import paths need to be updated.

**Comment by eduhenke** [comment]
Hi @michaelbironneau, sorry for the late response, I've just fixed this here https://github.com/voltbras/go-ocpp/commit/e879173b1b8851fe976c782fbfb294c371500862. But please, for the next fixes and improvements, you are welcome to submit PRs :)
