### ISSUE TITLE
Simplify usage of the CS/CP Service Send

### ISSUE THREAD

**Issue by eduhenke** [eduhenke/go-ocpp#2]
Currently, after sending the request(either a cpreq or a csreq), you get back a cpres/csres and an error.

To convert this cpres/csres back to the response type of the requested type, you have to do a type assertion, that consumes more 5 lines.

Solution ideas:
- Do the type assertion inside the .Send, and outside the function just ignore the type assertion "ok"
- Implement a Send{Heartbeat,RemoteStartTransaction,...} for every request/response pair, easier for the user to use, as it does not require type assertion, and the response given back is exactly the expected. However it duplicates a lot of code(though this lib does that a lot in the (cp/cs)(req/res) packages)

**Comment by elnapol** [comment]
Hello Eduhenke, Thank you so much for your work and effort put in this code, I wanted to ask if you have an example of the sending of commands from the server to the charging point as I have a charger and I can't make it start the charging process and from what I read in the OCPP protocol I am to understand that I have to start with 'RemoteStartTransaction' and I haven't been able to send the message from the server to the charger

**Comment by eduhenke** [comment]
Hello @elnapol,

It's my pleasure to know people are using this lib :)

I've added another example file in `example/cs/remote_unlock.go`, but the gist of it is this:

```go

cpID := "<CHARGEPOINT_ID>"
// cpURL is only used if it's SOAP
// if the communication is via WS
// the cpURL will be ignored
cpURL := "<CHARGEPOINT_URL>"
cpVersion := ocpp.V16

cpService, err := csys.GetServiceOf(cpID, cpVersion, cpURL)
if err != nil {
	panic(err)
}

// this is the RFID tag to be
// sent to the charger, if it's
// only a purely remote transaction(i.e. no local action needed)
// it can be anything(e.g. "VIRTUAL")
tag := "VIRTUAL"
cpResp, err := cpService.Send(&csreq.RemoteStartTransaction{
	IdTag:       tag,
	ConnectorId: 1,
})
if err != nil {
	// error on communicating
	panic(err)
}
resp := cpResp.(*csresp.RemoteStartTransaction)
if resp.Status != "Accepted" {
	panic("not accepted")
}
```

You first get a "service" to the ChargePoint, and then you send `CentralSystemRequest`s through the `Send` method in the service.

Just remembering that you need to have a running `CentralSystem`, i.e. you have to run the `Run` method of the `CentralSystem`.

Any more doubts please open a issue for this, and good luck with your project :)

**Comment by AlexMartSch** [comment]
> 
> 
> Hello @elnapol,
> 
> It's my pleasure to know people are using this lib :)
> 
> I've added another example file in `example/cs/remote_unlock.go`, but the gist of it is this:
> 
> ```go
> cpID := "<CHARGEPOINT_ID>"
> // cpURL is only used if it's SOAP
> // if the communication is via WS
> // the cpURL will be ignored
> cpURL := "<CHARGEPOINT_URL>"
> cpVersion := ocpp.V16
> 
> cpService, err := csys.GetServiceOf(cpID, cpVersion, cpURL)
> if err != nil {
> 	panic(err)
> }
> 
> // this is the RFID tag to be
> // sent to the charger, if it's
> // only a purely remote transaction(i.e. no local action needed)
> // it can be anything(e.g. "VIRTUAL")
> tag := "VIRTUAL"
> cpResp, err := cpService.Send(&csreq.RemoteStartTransaction{
> 	IdTag:       tag,
> 	ConnectorId: 1,
> })
> if err != nil {
> 	// error on communicating
> 	panic(err)
> }
> resp := cpResp.(*csresp.RemoteStartTransaction)
> if resp.Status != "Accepted" {
> 	panic("not accepted")
> }
> ```
> 
> You first get a "service" to the ChargePoint, and then you send `CentralSystemRequest`s through the `Send` method in the service.
> 
> Just remembering that you need to have a running `CentralSystem`, i.e. you have to run the `Run` method of the `CentralSystem`.
> 
> Any more doubts please open a issue for this, and good luck with your project :)

Hello  @eduhenke , 
Before, I hope you have a happy new year :)

I have a question with the same ask of elnapol, as I have a charger but I need sending commands from server to the client to get any response. I don't know how I can't do this, I try some things, inclusive with your example code but it's my first time with this and i cant get any response... I'm very frusted.

If you can help me with something more detailed or running program, I will be the human more happy in the world.

Thanks in advanced,
Alex.

**Comment by FlorishL** [comment]
Hello @eduhenke 

I am following this example/cs/remote_unlock.go, and executed code as you described but it throwing  below exception, 

2020/07/17 18:05:19 CP001
2020/07/17 18:05:19 http: panic serving [::1]:53522: no connection to this charge point

goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000196000)
        c:/go/src/net/http/server.go:1772 +0x140
panic(0x73dc80, 0xc0000420a0)
        c:/go/src/runtime/panic.go:975 +0x3f1
exit status 2


If you can help me with something more detailed as I am stuck at this point.

Thanks in advanced
FlorishL
