### ISSUE TITLE
Auto-Reconnect

### ISSUE THREAD

**Issue by AlexMartSch** [eduhenke/go-ocpp#3]
**Hello again!**
This time I come with a new question, something related with reconnect with the machine.
I explain you... we have a machine connected by LAN (testing environment). 

- We have a golang program running (with your files).
- We know that the machine auto reconnect on "Hard Reset".
- We know that the machine NO auto reconnect if the LAN cable is removed and put it again.  (Simulating a Wi-Fi connection with an interference or micro cuts)

**My solution?**
I know that when the machine is disconnected from LAN, in console appears a message -- `DEBUG: 18:01:10 Closed connection of: EFA06705` -- I'm thinking in capture the message and exec a function of reconnection, somehow remove go-routines or restart the program for reconnect with the machine.

Yes, is a rustic solution, but I don't know how is it the best solution.
Thanks in advance.

**Comment by eduhenke** [comment]
Hmm, weird. I've tested this lib in a real setting(through GSM chips, that consistently disconnect and lose its signal) and the charge points can reconnect. I saw that you closed the issue, have you found out about the problem?

**Comment by eduhenke** [comment]
And sorry about not commenting on the other issue, I was kind of busy :X
Happy new year to you too :)

**Comment by AlexMartSch** [comment]
@eduhenke 
Don't you worry friend, I understand.
Yes, effectly i committed a mistake, for some reason my machine can't reconnect,  but there are only a logic error of my code that i already fix it. 

Now i have a problem, with check the status of any connected machine. How I can get all machines connected and send commands for each one?

Hmm, in betters words.
- I have a web service that i send commands (for now to one machine)
- I need know when one machine lost connection for notify in the web interface. My unique solution is with arrays of connected machines and add/remove periodically the machine id for check.

**Comment by eduhenke** [comment]
I've added connection/disconnection listeners to the `CentralSystem` interface, maybe that can help you now?
