### ISSUE TITLE
Add security layer with identification of MAC address

### ISSUE THREAD

**Issue by oscarjairIT** [eduhenke/go-ocpp#4]
Hello Eduhenke, thanks for this great contribution. I'm starting with go and OCPP, and I would like to add some security feature with the addittion of the identification of the MAC address of the CP, is there any instance where to get this info?

Thanks in advanced!

**Comment by eduhenke** [comment]
Hello @oscarjairIT,

I'm not quite sure if it would be possible to grab the MAC address, as we receive a HTTP request with the station for SOAP connections and a Websocket connetion for JSON stations(https://stackoverflow.com/questions/3309122/how-can-i-get-a-mac-address-from-an-http-request), and that would make it not possible to grab the MAC address.

Depending on the chargepoint vendor you could add a layer of SSL.

But the info we have on this library, are the same that of a simple HTTP request. You could try messing around with the `DataTransfer` command of the chargepoint and try to think of a security mechanism using that information.

I've found this paper that might explicit some other security problems: https://www.researchgate.net/publication/313781416_OCPP_Protocol_Security_Threats_and_Challenges

There's also this link from the OCA, that would probably be the best and most canonical way to implement a secure connection:
https://www.openchargealliance.org/news/enhanced-security-for-ocpp-16/
