### ISSUE TITLE
GetServiceOf Method always received csys.conns map data Null

### ISSUE THREAD

**Issue by FlorishL** [eduhenke/go-ocpp#5]
Hi @eduhenke 

appreciated your hard work and effort for this lib but could you please look this method , It seems to me that this method cannot get a value of  csys.conns

func (csys *centralSystem) GetServiceOf(cpID string, version ocpp.Version, url string) (service.ChargePoint, error) {
	log.Debug("Current WS connections in service map : %v", csys.conns)
	log.Debug("Current WS connections in service map : %v", csys.conns[cpID])
	if version == ocpp.V15 {
		return service.NewChargePointSOAP(url, &soap.CallOptions{
			ChargeBoxIdentity: cpID,
			// TODO: insert IP address
			// From: <url>,
		}), nil
	}
	if version == ocpp.V16 {
		conn := csys.conns[cpID]
		if conn == nil { // TODO: or conn closed
			return nil, errors.New("no connection to this charge point")
		}
		return service.NewChargePointJSON(conn), nil
	}
	return nil, errors.New("charge point has no configured OCPP version(1.5/1.6)")
}
Thanks in advance

**Comment by eduhenke** [comment]
Hi, sorry for the late response :/

Was the issue solved?
